#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments
#------------------------------------------------------------------------------

echo "Building external libraries"
./WENOEXT/Allwmake

echo "Building application"
wmake $targetType laserDTRM
wmake $targetType phasesSystem
wmake $targetType interfaceProperties
wmake $targetType


#------------------------------------------------------------------------------
